Fix panic
Using the get endpoing results in this message

❯ ../target/debug/rucredstash get hi
thread 'main' panicked at 'Mismatch between definition and access of `credential`. Could not downcast to &alloc::string::String, need to downcast to alloc::string::String
', src/main.rs:615:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: clap_builder::parser::error::MatchesError::unwrap
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.4/src/parser/error.rs:32:9
   3: clap_builder::parser::matches::arg_matches::ArgMatches::get_one
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.4/src/parser/matches/arg_matches.rs:115:9
   4: rucredstash::CredstashApp::new_from
             at /home/sibi/github/rucredstash/src/main.rs:614:42
   5: rucredstash::CredstashApp::new
             at /home/sibi/github/rucredstash/src/main.rs:466:9
   6: rucredstash::main::{{closure}}
             at /home/sibi/github/rucredstash/src/main.rs:1016:25
   7: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:63
   8: tokio::runtime::coop::with_budget
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  10: tokio::runtime::park::CachedParkThread::block_on
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:31
  11: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/context.rs:315:13
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:66:9
  13: tokio::runtime::runtime::Runtime::block_on
             at /home/sibi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:304:45
  14: rucredstash::main
             at /home/sibi/github/rucredstash/src/main.rs:1017:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5